### ISSUE TITLE
Compliance Level recommendations

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite-1.0#1]
Change "Compliance Level" to "Compliance Level [ (Not a Finding) / (Not a Finding + Open + Not Reviewed) * 100% ]"

Also, change Compliance Level calculation to match.

**Comment by aaronlippold** [comment]
I would suggest that we follow the same pattern as the above elements - putting extra data on the next line, making the title of the element a bit larger and bold and the 'data' italics and non-bold + smaller.
