### ISSUE TITLE
dynamically add Profile Error tile

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite-1.0#21]
In the (hopefully rare) instance where a profile control returns "no result" either through poor coding or not running with appropriate credentials/authorization, dynamically add a stand-alone tile to the right of the findings block of four tiles. Label this "Profile Error", and below it in parenthesis:
(no result from test - check profile run privileges or author of profile)

**Comment by aaronlippold** [comment]
Can this be closed or added to another issue?

**Comment by ejaronne** [comment]
Right now it still says: "error running control, no **testes** ran" - why can't it say "(no result from test - check profile run privileges or author of profile)"? is my suggestion inaccurate? Note: this should only kick in for true coding errors or blocked access due to running with incorrect privilege.

**Comment by ejaronne** [comment]
Also, it still says "not tested" when the request is for it to say "Profile Error"

**Comment by dromazmj** [comment]
This has been added and tested a while ago. Closing
