### ISSUE TITLE
Assessment Audit Tracking modifcations

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite-1.0#34]
To keep the "CATT" report feature generic and closer to the original intent, please make these cosmetic modifications:

- Change "CATT Report" button to read: "Compliance Assessment/Audit Tracking (CAAT) Spreadsheet Download" <- important to use full thing as written for the button name, please.
- Change filename prefix from "CATT-" to "CAAT-"
- Remove "CFACTS" from column G header row
- Set all cells to Top Align and Wrap Text.

Thanks!

**Comment by rx294** [comment]
I have fixed everything except the cell formatting issue.

The **linkbreaks are in place** but it is some MS Excel issue that causes it to not activate....
if u double click the cell it formats correctly...
https://github.com/SheetJS/js-xlsx/issues/108

For now please select all cells and do `Wrap Text`,  `Format>Autofit Column Width` and `align top`

I will try and fix this issue soon

**Comment by ejaronne** [comment]
I spotting something else - please remove "CMS " from the file properties

**Comment by aaronlippold** [comment]
@rx294 as a general rule, don't specify any Sponsor name in any work that will be in the public domain.

**Comment by rx294** [comment]
I understand. Fixing now.

**Comment by aaronlippold** [comment]
Is this ticket resolved? Can we close it and link to a the merge of a PR or commit?

**Comment by rx294** [comment]
all are resolved except the excel cell formatting. 
Moving it to a new issue #40
Closing this.
