### ISSUE TITLE
Latest version does not work with IE again 

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite-1.0#36]
Can't seem to match "Version: v1.0.1-10-g41c0bc7" to a commit, but this version as of May 23 2018 doesn't work with IE. Debugger indicates 'load_views' is undefined?

![image](https://user-images.githubusercontent.com/34140975/44561968-4949c500-a725-11e8-945e-d6d802e5fb1e.png)

![image](https://user-images.githubusercontent.com/34140975/44562293-f2dd8600-a726-11e8-80fd-6e4bf6be431a.png)

**Comment by aaronlippold** [comment]
@dromazmj and @rx294 can you look at this today. Thanks.

**Comment by dromazmj** [comment]
fixed with #087c0e6d318a401cd983087ba9b5b7e0729bf564
