### ISSUE TITLE
What does "load a profile" mean?

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite-1.0#4]
commit f26cd0e introduced "Welcome to Heimdall-lite! Use the above to load a profile or a results json file."

I know how to load a json output file, but what does it mean to "load a profile"?

https://github.com/aaronlippold/heimdall-lite/commit/f26cd0e193b23c76c02574400f4e064ffab8170c

**Comment by dromazmj** [comment]
It would be the same as loading an evaulation in Heimdall2

**Comment by aaronlippold** [comment]
InSpec has two basic data sets in JSON - a Profile Data set which is just the data of the profile - i.e. no results - and the JSON Results. 

You can load both formats in Heimdall and review them.

**Comment by aaronlippold** [comment]
Perhaps we should adjust this to say - "Load InSpec JSON file" - We may also want to add a couple links on that section describing how you get both formats, examples of use and a small overview of what heimdall-lite can do.

**Comment by aaronlippold** [comment]
I think this can be closed with the addition of the landing page and added to the closed issues in the next push.
