### ISSUE TITLE
No wrapping in details tab

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite-1.0#5]
Text does not format or wrap in the details tab for control table. Can this be made to do so?

**Comment by dromazmj** [comment]
The text currently wraps when it hits the end of the table.  If it does not for you can you tell me what browser and operating system you use so I can recreate the issue.  Thank you

**Comment by ejaronne** [comment]
I am seeing the wrapping as you described. It would be nice if the wrapping mirrors the wrapping in the inspec code, i.e., recognizes CRs, LFs, and the wrapping in the inspec code check text, etc.

**Comment by ejaronne** [comment]
has this been resolved or is it tracked elsewhere?
